# Generated by Django 2.2.1 on 2019-05-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('admission', models.BigIntegerField()),
                ('form', models.CharField(choices=[('form 1', 'Form 1'), ('form 2', 'Form 2'), ('form 3', 'Form 3'), ('form 4', 'Form 4')], default='Form 1', max_length=6)),
                ('house', models.CharField(max_length=50)),
                ('club', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('department', models.CharField(choices=[('english', 'English'), ('maths', 'Maths'), ('swahili', 'Swahili'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Humanities', 'Humanities'), ('Grp4/5', 'Grp4/5')], default='Maths', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('year', models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], default=2018, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(choices=[('english', 'English'), ('maths', 'Maths'), ('swahili', 'Swahili'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Humanities', 'Humanities'), ('Grp4/5', 'Grp4/5')], default='Maths', max_length=45)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schapp.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('form 1', 'Form 1'), ('form 2', 'Form 2'), ('form 3', 'Form 3'), ('form 4', 'Form 4')], default='form 1', max_length=6)),
                ('cat', models.IntegerField(blank=True, null=True)),
                ('exam', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schapp.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schapp.Subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schapp.Term')),
            ],
        ),
    ]
