# Generated by Django 2.2.1 on 2019-05-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('admission', models.BigIntegerField(primary_key=True, serialize=False)),
                ('form', models.CharField(choices=[('form 1', 'Form 1'), ('form 2', 'Form 2'), ('form 3', 'Form 3'), ('form 4', 'Form 4')], default='Form 1', max_length=6)),
                ('house', models.CharField(max_length=50)),
                ('club', models.CharField(max_length=50)),
            ],
        ),
    ]
