# Generated by Django 2.2.1 on 2019-05-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='cat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='exam',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='remark',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
