# Generated by Django 2.2.1 on 2019-05-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schapp', '0002_auto_20190519_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='cat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='exam',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
