# Generated by Django 2.2.1 on 2019-05-19 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schapp', '0004_auto_20190519_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='cat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='exam',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schapp.Subject'),
        ),
    ]
