# Generated by Django 2.2.1 on 2019-05-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schapp', '0005_auto_20190519_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='remark',
            field=models.CharField(default=23, max_length=50),
            preserve_default=False,
        ),
    ]
