# Generated by Django 2.2.1 on 2019-05-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schapp', '0007_auto_20190519_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='cat',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='grade',
            name='exam',
            field=models.CharField(max_length=3),
        ),
    ]
