# Generated by Django 2.2.1 on 2019-05-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schapp', '0008_auto_20190519_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.CharField(choices=[('english', 'English'), ('maths', 'Maths'), ('swahili', 'Swahili'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Humanities', 'Humanities'), ('Grp4/5', 'Grp4/5')], default='Maths', max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('english', 'English'), ('maths', 'Maths'), ('swahili', 'Swahili'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Humanities', 'Humanities'), ('Grp4/5', 'Grp4/5')], default='Maths', max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
